test:
  value1: 123456g
db:
  dsn: "root:rootlxj0@tcp(localhost:13316)/webook?charset=utf8mb4&parseTime=True"
redis:
  addr: "localhost:16379"
kafka:
  addr:
    - "localhost:9094"
grpc:
  server:
#    这里直接默认localhost有可能会出问题
    addr: ":8090"
  client:
    addr: