test:
  value1: 123456g
db:
  dsn: "root:root@tcp(172.27.19.245:13316)/webook?charset=utf8mb4&parseTime=True"
redis:
  addr: "localhost:6379"
kafka:
  addr:
    - "172.27.19.245:9094"


grpc:
  client:
    intr:
      addr: "localhost:8090"
      threshold: 10