test:
  value1: 123456g
db:
  dsn: "root:rootlxj0@tcp(localhost:13316)/webook?charset=utf8mb4&parseTime=True"
redis:
  addr: "127.0.0.2:16379"
kafka:
  addr:
    - "localhost:9094"


grpc:
  client:
    intr:
      addr: "localhost:8090"
      threshold: 10