// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"project0/internal/repository"
	"project0/internal/repository/cache"
	"project0/internal/repository/dao"
	"project0/internal/service"
	"project0/internal/web"
	"project0/internal/web/ijwt"
	"project0/ioc"
)

// Injectors from wire.go:

// 首要的main先初始化webServer
func InitWebServerJ() *gin.Engine {
	cmdable := InitRedis()
	handler := ijwt.NewRedisJWTHandler(cmdable)
	loggerV1 := InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, handler, loggerV1)
	db := InitDB()
	userDao := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewCacheUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	v2 := ioc.NewSMSS()
	limiter := ioc.InitRedisLimiter(cmdable)
	smsService := ioc.InitSMSService(v2, limiter)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	wechatService := InitWechatService(loggerV1)
	oAuth2Handler := web.NewOAuth2Handler(wechatService, userService, handler)
	articleDao := dao.NewArticleGROMDAO(db)
	articleRepository := repository.NewCacheArticleRepository(articleDao)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := web.NewArticleHandler(articleService, loggerV1)
	engine := ioc.InitWebServer(v, userHandler, oAuth2Handler, articleHandler)
	return engine
}

func InitArticleHandler(dao2 dao.ArticleDao) *web.ArticleHandler {
	articleRepository := repository.NewCacheArticleRepository(dao2)
	articleService := service.NewArticleService(articleRepository)
	loggerV1 := InitLogger()
	articleHandler := web.NewArticleHandler(articleService, loggerV1)
	return articleHandler
}

// wire.go:

var thirdPartySet = wire.NewSet(
	InitDB, InitRedis, InitLogger, ioc.InitRedisLimiter, ioc.NewSMSS,
)
